language: go
go:
- 1.15.x
sudo: false
script:
- make build
- make darwin
- make freebsd
before_deploy:
- mkdir -p bin_release
- CGO_ENABLED=0 GOOS=linux   GOARCH=amd64 go build -a -ldflags "-extldflags '-static'
  -X main.AppVersion=$TRAVIS_TAG" -o bin_release/freenas-provisioner_linux-amd64
- CGO_ENABLED=0 GOOS=darwin  GOARCH=amd64 go build -a -ldflags "-extldflags '-static'
  -X main.AppVersion=$TRAVIS_TAG" -o bin_release/freenas-provisioner_darwin-amd64
- CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -a -ldflags "-extldflags '-static'
  -X main.AppVersion=$TRAVIS_TAG" -o bin_release/freenas-provisioner_freebsd-amd64
- CGO_ENABLED=0 GOOS=linux   GOARCH=arm   go build -a -ldflags "-extldflags '-static'
  -X main.AppVersion=$TRAVIS_TAG" -o bin_release/freenas-provisioner_linux-arm
deploy:
  provider: releases
  api_key:
    secure: 17OLWyqB+B/tH/hVLP1zTD1bF2earEhwKdxH6SJpgdUcvUKL2IcKoRn+zrDc+QandVPtJpCV9Wdj8xK5slRVT0dxzKUwFH2SzagAoj+mKkJ6Ks9ZeW060psU62lHlhlP2N74BwWK9+cmRyUq6D4moy2BrnWsl67BnyCTQikP4wRDt1H1t3f9xefjqslQX3Y3+mrQnNc1cXA2Yj2Emvm3uyX3c3gXhiYvjxFTopB9XYfg2ftXMN9aqVwAcwioXwfHWF82jDxWBJXIelcv8SbN4gUHBbko3oP89uNCauKJePTsaBcszh5UbhhgkXWenBTLNhkzhFhJQpZfIK970QDMZjB7W1CB2roj22U1+pjVSPvx+/OiCUpS4PkXoZuPKSuXmvTcfFLliMVmKDmj08tTblKjkB31zr4Q01DxKvZDU2UzhsPFz1nQzo+6OD2HP4YWzqxzf5EejgLDr0+AQx5MNKxbcipI5Z/BjVWGihgoQNsbDrfwRGeL4yDa//EC2TsAkxRceiTsxDf0EGpg4syUcyIHGIyi+4D9NVihid4BDE3sW0mNFjaGgOrgSHp1lYqNHOJn4piSFHcJaDFW4oNt5IHJIeIe2FawUabPBzKd4i7D1qoQZWBDOb980kbNe81AM3vpY/yh3owpontqoBtBYS/Enl1bDLWc6D624xz/6Ok=
  file_glob: true
  file: bin_release/*
  skip_cleanup: true
  on:
    tags: true
  go: 1.15.x
