language: go
go:
- 1.15.x
sudo: false
script:
- make build
- make darwin
- make freebsd
before_deploy:
- mkdir -p bin_release
- CGO_ENABLED=0 GOOS=linux   GOARCH=amd64 go build -a -ldflags "-extldflags '-static'
  -X main.AppVersion=$TRAVIS_TAG" -o bin_release/freenas-provisioner_linux-amd64
- CGO_ENABLED=0 GOOS=darwin  GOARCH=amd64 go build -a -ldflags "-extldflags '-static'
  -X main.AppVersion=$TRAVIS_TAG" -o bin_release/freenas-provisioner_darwin-amd64
- CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -a -ldflags "-extldflags '-static'
  -X main.AppVersion=$TRAVIS_TAG" -o bin_release/freenas-provisioner_freebsd-amd64
- CGO_ENABLED=0 GOOS=linux   GOARCH=arm   go build -a -ldflags "-extldflags '-static'
  -X main.AppVersion=$TRAVIS_TAG" -o bin_release/freenas-provisioner_linux-arm
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API_KEY
  file_glob: true
  file: bin_release/*
  skip_cleanup: true
  on:
    tags: true
  go: 1.15.x
